const invoke = window.__TAURI__.core.invoke;
const $ = (selector) => document.querySelector(selector);
const views = {player:'Listen without leaving.',models:'Choose the engine.',voices:'A voice, held locally.',history:'What you heard.',settings:'Make it yours.'};
let snapshot = null;
let historyItems = [];
let recordingTimer = null;
let recordingStopping = false;
let preparedRecordingPath = null;

document.querySelectorAll('.nav-item').forEach(button => button.addEventListener('click', () => {
  document.querySelectorAll('.nav-item,.view').forEach(item => item.classList.remove('active'));
  button.classList.add('active');
  $(`#${button.dataset.view}-view`).classList.add('active');
  $('#view-title').textContent = views[button.dataset.view];
  $('#eyebrow').textContent = button.textContent.replace(/^\d+/, '').trim().toUpperCase();
  refresh(button.dataset.view);
}));

async function get(resource){ return invoke('service_get',{resource}); }
async function post(resource,body=null){ return invoke('service_post',{resource,body}); }
async function del(resource){ return invoke('service_delete',{resource}); }
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function time(value=0){const seconds=Math.max(0,Math.floor(value));return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`}

async function refresh(section='player'){
  try{
    snapshot=await get('state');
    $('#service-pill').classList.remove('offline');$('#service-pill').innerHTML='<i></i>Service ready';
    await renderPlayer(snapshot);
    if(section==='models') renderModels(await get('models'));
    if(section==='voices'){const [voices,settings,models]=await Promise.all([get('voices'),get('settings'),get('models')]);renderVoices(voices,settings,models)}
    if(section==='history'){historyItems=await get('history');renderHistory(historyItems)}
    if(section==='settings') await renderSettings(await get('settings'));
  }catch(error){$('#service-pill').classList.add('offline');$('#service-pill').innerHTML='<i></i>Service offline';console.error(error)}
}

function renderSpokenText(playback){const container=$('#spoken-text');if(!playback.spoken_text){container.textContent='Select text anywhere, then use your shortcut. Your words will appear here as they’re spoken.';return}const characters=Array.from(playback.spoken_text);const chunks=playback.spoken_chunks||[];if(!chunks.length){container.textContent=playback.spoken_text;return}let active=0;for(let index=0;index<chunks.length;index++)if(chunks[index].audio_start_seconds<=playback.position_seconds)active=index;container.replaceChildren();let cursor=0;chunks.forEach((chunk,index)=>{if(chunk.text_start>cursor)container.append(document.createTextNode(characters.slice(cursor,chunk.text_start).join('')));const span=document.createElement('span');span.className=`lyric-chunk${index===active?' current':index<active?' spoken':''}`;if(index===active)span.setAttribute('aria-current','true');span.textContent=characters.slice(chunk.text_start,chunk.text_end).join('');container.append(span);cursor=chunk.text_end});if(cursor<characters.length)container.append(document.createTextNode(characters.slice(cursor).join('')))}
async function renderPlayer(state){const p=state.playback;$('#position').textContent=time(p.position_seconds);$('#duration').textContent=time(p.duration_seconds);$('#timeline-fill').style.width=`${p.duration_seconds?Math.min(100,p.position_seconds/p.duration_seconds*100):0}%`;$('#play-toggle').textContent=p.state==='paused'?'▶':'Ⅱ';$('#rate').value=String(p.rate);$('#volume').value=p.volume;const title=$('#now-title');title.textContent=p.current_title||'';title.hidden=!p.current_title;renderSpokenText(p)}

function renderModels(models){$('#model-list').innerHTML=models.map(model=>{const d=model.download;const busy=d&&['downloading','verifying','installing'].includes(d.state);const progress=d?Math.round(d.downloaded_bytes/Math.max(1,d.total_bytes)*100):0;const primary=model.selected?'<button class="action secondary" disabled>In use</button>':`<button class="action ${model.installed?'secondary':''}" data-model="${escapeHtml(model.id)}" data-action="${model.installed?'select':'install'}">${model.installed?'Use this model':'Download'}</button>`;const benchmark=model.benchmark?`<div class="benchmark"><strong>${model.benchmark.mean_rtf.toFixed(2)}× RTF</strong><span>cold ${Math.round(model.benchmark.cold_start_ms)} ms · p95 ${Math.round(model.benchmark.p95_ms)} ms</span></div>`:'';const installedActions=model.installed?`${model.update_available?`<button class="action secondary" data-model="${escapeHtml(model.id)}" data-action="update">Update</button>`:''}<button class="action secondary" data-model="${escapeHtml(model.id)}" data-action="benchmark">Benchmark</button>${model.resident?`<button class="action secondary" data-model="${escapeHtml(model.id)}" data-action="unload">Unload</button>`:''}${model.selected?'':`<button class="action secondary danger" data-model="${escapeHtml(model.id)}" data-action="remove">Remove</button>`}`:'';return `<article class="data-card"><header><div><h3>${escapeHtml(model.name)}</h3><div class="tags"><span class="tag">${escapeHtml(model.languages.join(', '))}</span>${model.capabilities.voice_cloning?'<span class="tag accent">Voice cloning</span>':''}${model.selected?'<span class="tag accent">Selected</span>':''}${model.resident?'<span class="tag accent">Loaded</span>':''}${model.update_available?'<span class="tag accent">Update available</span>':''}${model.recommended?'<span class="tag accent">Fastest measured</span>':''}</div></div><span>${Math.round(model.size_bytes/1048576)} MB</span></header><p>${escapeHtml(model.quality_note)}</p><p><small>${escapeHtml(model.speed_note)} · ${escapeHtml(model.license)} license</small></p>${benchmark}${busy?`<div class="progress"><div style="width:${progress}%"></div></div><small>${escapeHtml(d.state)} · ${progress}%</small><div class="card-actions"><button class="action secondary danger" data-model="${escapeHtml(model.id)}" data-action="cancel">Cancel</button></div>`:`<div class="card-actions">${primary}${installedActions}</div>`}</article>`}).join('');document.querySelectorAll('[data-model]').forEach(button=>button.onclick=()=>modelAction(button))}
async function modelAction(button){const {model,action}=button.dataset;try{button.disabled=true;if(action==='remove')await del(`models/${model}`);else await post(`models/${model}/${action}`);toast(action==='install'?'Download started':action==='update'?'Model update started':action==='cancel'?'Download cancellation requested':action==='remove'?'Model removed':action==='unload'?'Model unloaded':action==='benchmark'?'Local benchmark complete':'Model selected');refresh('models')}catch(error){button.disabled=false;toast(String(error))}}

function renderVoices(voices,settings,models){const selected=settings.active_voice_profile_id;const model=models.find(candidate=>candidate.selected);const builtIns=(model?.preset_voices||[]).map(voice=>{const active=!selected&&voice.selected;return `<article class="data-card"><header><h3>${escapeHtml(voice.name)}</h3><div><span class="tag">${escapeHtml(voice.language)}</span>${active?' <span class="tag accent">Selected</span>':''}</div></header><p>Built into ${escapeHtml(model.name)} · processed locally.</p><div class="card-actions">${active?'<button class="action secondary" disabled>In use</button>':`<button class="action secondary" data-preset-model="${escapeHtml(model.id)}" data-preset-voice="${escapeHtml(voice.id)}">Use this voice</button>`}</div></article>`}).join('');const noVoice=!builtIns&&!voices.length?'<p class="empty">This model needs a cloned voice. Record or import a permitted reference sample below.</p>':'';const clones=voices.map(voice=>{const active=voice.id===selected;const quality=voice.quality||{};const issues=(quality.issues||[]).map(issue=>`<li>${escapeHtml(issue)}</li>`).join('');return `<article class="data-card"><header><h3>${escapeHtml(voice.name)}</h3><div><span>${voice.reference_duration_seconds.toFixed(1)} sec</span>${active?' <span class="tag accent">Selected</span>':''}</div></header><p>Local reference profile · created ${new Date(voice.created_at).toLocaleDateString()}</p>${quality.sample_rate?`<div class="voice-quality"><strong>${quality.quality_score}/100</strong><span>${Math.round(quality.sample_rate/1000)} kHz · RMS ${quality.rms_dbfs.toFixed(1)} dBFS · clipped ${quality.clipped_sample_percent.toFixed(2)}%</span></div>${issues?`<ul class="quality-issues">${issues}</ul>`:''}`:''}<div class="card-actions"><button class="action" data-voice="${voice.id}" data-voice-action="preview">Preview</button>${active?'<button class="action secondary" disabled>In use</button>':`<button class="action secondary" data-voice="${voice.id}" data-voice-action="select">Use this voice</button>`}<button class="action secondary" data-voice="${voice.id}" data-voice-action="rename" data-voice-name="${escapeHtml(voice.name)}">Rename</button>${active?'':`<button class="action secondary danger" data-voice="${voice.id}" data-voice-action="delete">Delete</button>`}</div></article>`}).join('');$('#voice-list').innerHTML=builtIns+noVoice+clones;document.querySelectorAll('[data-voice]').forEach(button=>button.onclick=()=>voiceAction(button));document.querySelectorAll('[data-preset-voice]').forEach(button=>button.onclick=()=>presetVoiceAction(button))}
async function refreshVoices(){const [voices,settings,models]=await Promise.all([get('voices'),get('settings'),get('models')]);renderVoices(voices,settings,models)}
async function voiceAction(button){const {voice:id,voiceAction:action,voiceName}=button.dataset;try{if(action==='delete')await del(`voices/${id}`);else if(action==='rename'){const name=window.prompt('Voice name',voiceName);if(!name)return;await post(`voices/${id}/rename`,{name})}else await post(`voices/${id}/${action}`);toast(action==='preview'?'Voice preview queued':'Voice profiles updated');await refreshVoices()}catch(error){toast(String(error))}}
async function presetVoiceAction(button){try{button.disabled=true;await post(`models/${button.dataset.presetModel}/voices/${button.dataset.presetVoice}/select`);toast('Built-in voice selected');await refreshVoices()}catch(error){button.disabled=false;toast(String(error))}}
function renderHistory(items){const query=$('#history-search').value.trim().toLocaleLowerCase();const filtered=query?items.filter(item=>item.job.text.toLocaleLowerCase().includes(query)):items;$('#history-list').innerHTML=filtered.length?filtered.map(item=>`<article class="data-card"><header><h3>${item.pinned?'◆ ':''}${escapeHtml(item.job.text.slice(0,96))}${item.job.text.length>96?'…':''}</h3><span>${time(item.duration_seconds)}</span></header><p>${new Date(item.job.created_at).toLocaleString()} · ${escapeHtml(item.job.source)}</p><div class="card-actions"><button class="action" data-history="${item.job.id}" data-history-action="replay" ${item.audio_path?'':'disabled'}>Replay</button><button class="action secondary" data-history="${item.job.id}" data-history-action="regenerate">Regenerate</button><button class="action secondary" data-history="${item.job.id}" data-history-action="export" ${item.audio_path?'':'disabled'}>Export WAV</button><button class="action secondary" data-history="${item.job.id}" data-history-action="pin" data-pinned="${item.pinned}">${item.pinned?'Unpin':'Pin'}</button><button class="action secondary danger" data-history="${item.job.id}" data-history-action="delete">Delete</button></div></article>`).join(''):`<p class="empty">${query?'No history matches your search.':'Your listening history is empty.'}</p>`;document.querySelectorAll('[data-history]').forEach(button=>button.onclick=()=>historyAction(button))}
async function historyAction(button){const {history:id,historyAction:action,pinned}=button.dataset;try{if(action==='delete')await del(`history/${id}`);else if(action==='pin')await post(`history/${id}/pin`,{pinned:pinned!=='true'});else if(action==='export'){const item=historyItems.find(entry=>entry.job.id===id);const destination=window.prompt('Save WAV as',`say-the-rest-${id}.wav`);if(!destination)return;await invoke('export_history',{source:item.audio_path,destination})}else await post(`history/${id}/${action}`);toast(action==='replay'?'Replaying archived audio':action==='regenerate'?'Fresh audio queued':action==='export'?'WAV exported':'History updated');historyItems=await get('history');renderHistory(historyItems)}catch(error){toast(String(error))}}
function escapeHtml(text){const el=document.createElement('span');el.textContent=text;return el.innerHTML}
function ensureStartupControl(form){if(form.elements.launch_at_login)return;const label=document.createElement('label');label.className='consent';label.innerHTML='<input name="launch_at_login" type="checkbox"><span>Start the speech service and shortcut tray when I sign in</span>';form.insertBefore(label,form.querySelector('button[type=submit]'))}
function showShortcuts(settings){const display=value=>value.split('+').map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(' + ');$('#selection-shortcut-label').textContent=display(settings.selection_shortcut);$('#clipboard-shortcut-label').textContent=display(settings.clipboard_shortcut);const form=$('#shortcut-form');ensureStartupControl(form);form.elements.selection_shortcut.value=settings.selection_shortcut;form.elements.clipboard_shortcut.value=settings.clipboard_shortcut;form.elements.launch_at_login.checked=settings.launch_at_login!==false}
function ensureCleaningControls(form){if(form.querySelector('#text-cleaning-controls'))return;const fieldset=document.createElement('fieldset');fieldset.id='text-cleaning-controls';fieldset.className='settings-fieldset';fieldset.innerHTML='<legend>Text cleaning</legend><p>Clean copied document and webpage text before it enters speech or history.</p><label class="consent"><input name="cleaning_enabled" type="checkbox"><span>Enable text cleaning</span></label><div class="cleaning-options"><label class="consent"><input name="strip_markdown" type="checkbox"><span>Strip Markdown formatting</span></label><label class="consent"><input name="strip_html" type="checkbox"><span>Strip HTML formatting</span></label><label class="consent"><input name="strip_code_blocks" type="checkbox"><span>Remove fenced code blocks</span></label><label class="consent"><input name="strip_special_characters" type="checkbox"><span>Remove invisible clipboard artifacts</span></label><label class="consent"><input name="normalize_whitespace" type="checkbox"><span>Normalize whitespace</span></label></div>';form.insertBefore(fieldset,form.querySelector('button[type=submit]'));form.elements.cleaning_enabled.onchange=()=>syncCleaningControls(form)}
function syncCleaningControls(form){const enabled=form.elements.cleaning_enabled.checked;form.querySelectorAll('.cleaning-options input').forEach(input=>input.disabled=!enabled)}
async function renderSettings(settings){const form=$('#settings-form');ensureCleaningControls(form);form.elements.speaking_pace.value=String(settings.speaking_pace);form.elements.model_timeout_minutes.value=Math.round(settings.model_unload_delay_seconds/60);form.elements.history_retention_days.value=String(settings.history_retention_days||0);form.elements.history_quota_mb.value=Math.round(settings.history_quota_bytes/1048576);form.elements.long_text_characters.value=settings.long_text_confirmation_characters;const cleaning=settings.text_cleaning||{enabled:true,strip_markdown:true,strip_html:true,strip_code_blocks:true,strip_special_characters:true,normalize_whitespace:true};for(const name of ['enabled','strip_markdown','strip_html','strip_code_blocks','strip_special_characters','normalize_whitespace'])form.elements[name==='enabled'?'cleaning_enabled':name].checked=Boolean(cleaning[name]);syncCleaningControls(form);const models=await get('models');const active=models.find(model=>model.selected);form.elements.speaking_pace.disabled=!active?.supports_native_speaking_pace;$('#speaking-pace-note').textContent=active?.supports_native_speaking_pace?'Shapes phoneme timing in newly generated audio. Existing history is unchanged.':'The selected model does not expose native speaking pace; it uses its natural pace.';showShortcuts(await invoke('desktop_settings'));const diagnostics=await invoke('desktop_diagnostics');$('#diagnostics').innerHTML=`<h3>Diagnostics</h3><dl><div><dt>Platform</dt><dd>${escapeHtml(diagnostics.platform)} / ${escapeHtml(diagnostics.architecture)}</dd></div><div><dt>Desktop session</dt><dd>${escapeHtml(diagnostics.session)}</dd></div><div><dt>Selection access</dt><dd>${escapeHtml(diagnostics.selection_support)}</dd></div><div><dt>Launch at login</dt><dd>${diagnostics.launch_at_login_active?'Enabled':diagnostics.launch_at_login_requested?'Requested, but service is not enabled':'Disabled'}</dd></div><div><dt>Service credentials</dt><dd>${diagnostics.token_available?'Ready':'Unavailable'}</dd></div></dl>`}

$('#play-toggle').onclick=()=>post(`playback/${snapshot?.playback.state==='paused'?'resume':'pause'}`).then(()=>refresh()).catch(error=>toast(String(error)));
document.querySelector('[data-control=seek-back]').onclick=()=>post('playback/seek',{seconds:Math.max(0,(snapshot?.playback.position_seconds||0)-15)}).then(()=>refresh());
document.querySelector('[data-control=seek-forward]').onclick=()=>post('playback/seek',{seconds:(snapshot?.playback.position_seconds||0)+15}).then(()=>refresh());
$('#rate').onchange=event=>post('playback/rate',{rate:Number(event.target.value)}).catch(error=>toast(String(error)));
$('#volume').onchange=event=>post('playback/volume',{volume:Number(event.target.value)}).catch(error=>toast(String(error)));
function setRecordingUi(status){const active=status.recording;$('#record-start').disabled=active;$('#record-stop').disabled=!active;$('#record-cancel').disabled=!active;$('#recording-time').textContent=`${status.elapsed_seconds.toFixed(1)} sec`;$('#recording-state').textContent=active?'Recording locally… speak one or two natural sentences':'Use your default microphone'}
async function pollRecording(){try{const status=await invoke('voice_recording_status');setRecordingUi(status);if(status.recording&&status.elapsed_seconds>=status.maximum_seconds-.1)await finishRecording()}catch(error){clearInterval(recordingTimer);recordingTimer=null;toast(String(error))}}
async function finishRecording(){if(recordingStopping)return;recordingStopping=true;try{const result=await invoke('stop_voice_recording');clearInterval(recordingTimer);recordingTimer=null;preparedRecordingPath=result.path;$('#voice-form').elements.path.value=result.path;setRecordingUi({recording:false,elapsed_seconds:result.duration_seconds});$('#record-cancel').disabled=false;$('#record-cancel').textContent='Discard';$('#recording-state').textContent='Recording ready · create the voice profile to analyze it';toast('Recording ready for quality analysis')}catch(error){toast(String(error))}finally{recordingStopping=false}}
$('#record-start').onclick=async()=>{try{if(preparedRecordingPath)await invoke('discard_voice_recording',{path:preparedRecordingPath});const status=await invoke('start_voice_recording');preparedRecordingPath=null;$('#record-cancel').textContent='Cancel';$('#voice-form').elements.path.value='';setRecordingUi(status);recordingTimer=setInterval(pollRecording,100)}catch(error){toast(String(error))}};
$('#record-stop').onclick=finishRecording;
$('#record-cancel').onclick=async()=>{try{if(preparedRecordingPath){await invoke('discard_voice_recording',{path:preparedRecordingPath});preparedRecordingPath=null;$('#voice-form').elements.path.value=''}else await invoke('cancel_voice_recording');clearInterval(recordingTimer);recordingTimer=null;$('#record-cancel').textContent='Cancel';setRecordingUi({recording:false,elapsed_seconds:0});toast('Recording discarded')}catch(error){toast(String(error))}};
$('#voice-form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.target);const path=String(data.get('path')).trim();if(!path){toast('Record a sample or choose a reference WAV first');return}try{await post('voices',{name:data.get('name'),reference_audio_path:path,speaker_permission_confirmed:data.get('consent')==='on'});if(path===preparedRecordingPath)invoke('discard_voice_recording',{path}).catch(console.error);preparedRecordingPath=null;event.target.reset();setRecordingUi({recording:false,elapsed_seconds:0});toast('Voice profile created');await refreshVoices()}catch(error){toast(String(error))}};
$('#history-search').oninput=()=>renderHistory(historyItems);
$('#settings-form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.target);try{const settings=await post('settings',{speaking_pace:event.target.elements.speaking_pace.disabled?null:Number(data.get('speaking_pace')),model_unload_delay_seconds:Number(data.get('model_timeout_minutes'))*60,history_retention_days:Number(data.get('history_retention_days')),history_quota_bytes:Number(data.get('history_quota_mb'))*1048576,long_text_confirmation_characters:Number(data.get('long_text_characters')),text_cleaning:{enabled:data.get('cleaning_enabled')==='on',strip_markdown:data.get('strip_markdown')==='on',strip_html:data.get('strip_html')==='on',strip_code_blocks:data.get('strip_code_blocks')==='on',strip_special_characters:data.get('strip_special_characters')==='on',normalize_whitespace:data.get('normalize_whitespace')==='on'}});renderSettings(settings);toast('Settings saved')}catch(error){toast(String(error))}};
$('#shortcut-form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.target);try{const settings=await invoke('update_desktop_settings',{settings:{selection_shortcut:String(data.get('selection_shortcut')).trim().toLowerCase(),clipboard_shortcut:String(data.get('clipboard_shortcut')).trim().toLowerCase(),launch_at_login:data.get('launch_at_login')==='on'}});showShortcuts(settings);toast('Shortcut and startup settings updated')}catch(error){toast(String(error))}};
$('#model-import-form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.target);try{await post('models/imports/local',{directory:data.get('directory'),display_name:data.get('display_name'),license:data.get('license'),license_url:data.get('license_url'),untested_model_and_license_review_confirmed:data.get('acknowledged')==='on'});event.target.reset();toast('Community model imported');refresh('models')}catch(error){toast(String(error))}};
$('#hf-import-form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.target);try{toast('Resolving immutable repository revision…');await post('models/imports/huggingface',{repository:data.get('repository'),revision:data.get('revision')||null,display_name:data.get('display_name'),license:data.get('license'),license_url:data.get('license_url'),access_token:data.get('access_token')||null,untested_model_and_license_review_confirmed:data.get('acknowledged')==='on'});event.target.reset();toast('Hugging Face model imported');refresh('models')}catch(error){toast(String(error))}};
invoke('desktop_settings').then(showShortcuts).catch(console.error);setInterval(()=>refresh(document.querySelector('.nav-item.active').dataset.view),1000);refresh();
window.__TAURI__.event.listen('capture-status',event=>{const status=event.payload;if(status.ok){toast(`${status.kind==='selection'?'Selection':'Clipboard'} sent to speech`);refresh()}else{toast(status.error||'Text could not be captured')}});
window.__TAURI__.event.listen('long-text-request',async event=>{const request=event.payload;const confirmed=window.confirm(`This ${request.kind} contains ${request.characters.toLocaleString()} characters and may take a while to process. Read it aloud?`);if(!confirmed){toast('Long text was not queued');return}try{await post('jobs',{text:request.text,source:request.kind,queue_policy:'replace',confirmed_long_text:true});toast('Long text queued');refresh()}catch(error){toast(String(error))}});
const onboarding=$('#onboarding');async function showOnboardingWhenNeeded(){try{const hasModel=(await get('models')).some(model=>model.installed);if(!hasModel||!localStorage.getItem('onboarding-complete'))onboarding.showModal()}catch(error){console.error(error)}}onboarding.addEventListener('close',()=>{localStorage.setItem('onboarding-complete','true');document.querySelector('[data-view="models"]').click()});showOnboardingWhenNeeded();
