[package]
name = "sayit-service-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sayit-service"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
sayit-service = { path = "../../crates/service" }
tokio.workspace = true
