[package]
name = "sayit"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
reqwest.workspace = true
serde_json.workspace = true
sayit-core = { path = "../../crates/core" }
sayit-protocol = { path = "../../crates/protocol" }
uuid.workspace = true
